name = "PlutoUtils"
uuid = "a5ec66cb-57bb-4ae5-9259-3342d9ed6c94"
license = "Unlicense"
authors = ["Fons van der Plas <fonsvdplas@gmail.com>"]
version = "0.0.1"

[deps]
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
Pluto = "0.11"
