name = "PlutoUtils"
uuid = "a5ec66cb-57bb-4ae5-9259-3342d9ed6c94"
license = "Unlicense"
authors = ["Fons van der Plas <fonsvdplas@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
GitHubActions = "6b79fd1a-b13a-48ab-b6b0-aaee1fee41df"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
GitHubActions = "0.1"
Pluto = "0.14"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]